name = "form-soc-it-backend"
main = "worker.js"
compatibility_date = "2024-05-31"

# === Cloudflare KV Binding (Para guardar los datos de texto) ===
# Necesitas crear este namespace en Cloudflare y reemplazar el ID abajo.
[[kv_namespaces]]
binding = "SOLICITUDES_KV"
id = "57b4bb86a9c746bfb2337c2c56518fc1"

# === Cloudflare R2 Binding (Para guardar los archivos adjuntos) ===
# Necesitas crear este bucket en Cloudflare R2.
[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "form-soc-it-uploads"
